# -*- coding: utf-8 -*-
"""Rock Paper And Scissors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x9E7uORh9GluE4EpbvAYXhF4qerMXgC_
"""

import random
player_choice = input("Enter player choice(Rock, Paper, Scissors) :\n")
l1 = ["Rock","Paper","Scissors"]
if  player_choice not in l1:
    print("Invalid Input")
else:
    options = ("Rock","Paper","Scissors")
    computer_choice = random.choice(options)
    print("Computer Choice:",computer_choice)
    if computer_choice == player_choice:
        print("It's a tie.")
    elif computer_choice == "Scissors" and player_choice == "Rock":
        print("Player Wins")
    elif computer_choice == "Rock" and player_choice == "Paper":
        print("Player Wins")
    elif computer_choice == "Paper" and player_choice == "Scissors":
        print("Player Wins")
    else:
        print("Player Lose!")