# -*- coding: utf-8 -*-
"""Simple Calculator

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f43QlKdzrqNSu0I9XpA7MEE9PXisVpuV
"""

print("SIMPLE CALCULATOR")
num1 = float(input("Enter num1 : "))
num2 = float(input("Enter num2 : "))
print("Enter 1 for Addition\nEnter 2 for Subtraction\nEnter 3 for Multiplication\nEnter 4 for Division")
choice = int(input("Enter your choice : "))
if choice == 1:
  print("The sum of numbers is :",num1+num2)
elif choice == 2:
  print("The subtraction of numbers is :",num1-num2)
elif choice == 3:
   print("The multiplicaton of numbers is :",num1*num2)
elif choice == 4:
   print("The division of numbers is :",num1/num2)
else:
  print("Invalid input")